### ISSUE TITLE
Handling nvidia-smi timeout

### ISSUE THREAD

**Issue by Lupul** [xstead/ethereum-miner-monitor#3]
```
# line 403:
shell_cmd = 'nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits'
output = self.run_shell_cmd(shell_cmd)
gpu_utilization_list = output.split('\n')
```
When nvidia-smi timeouts, the 'output' var. will be set to  'None' so output.split('\n') will raise an error.
This timeout means that at least one of the cards has problems. This state is in my experience unrecoverable without a reboot.

**Comment by xstead** [comment]
Hi,
Thanks!
#line 403 , output None is fixed with try/catch.

If your system is running normally the "nvidia-smi" must have return the result within 1-2 sec. (the timeout is 30sec for running shell commands), otherwise this "empty" output will generate only an ERROR. When the monitor can't get the GPU utilization data, it cant decide what to do. (not going to reboot)
